apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel.fullname" . }}-api
  labels:
    {{- include "sentinel.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "sentinel.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentinel.api.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-postgresql 5432; do echo "waiting for postgres..."; sleep 3; done']
        - name: wait-for-kafka
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-kafka 9092; do echo "waiting for kafka..."; sleep 3; done']
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sentinel.fullname" . }}-api-secrets
                  key: db-password
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
