apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.fullname" . }}-api-secrets
  labels:
    {{- include "sentinel.api.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
